//characters list 
export const FETCHCHARACTERSLISTLOADING = "FETCHCHARACTERSLOADING";
export const FETCHCHARACTERSLISTSUCCESS = "FETCHCHARACTERSSUCCESS";
export const FETCHCHARACTERSLISTERROR = "FETCHCHARACTERSERROR";

//character details 
export const FETCHCHARACTERLOADING = "FETCHCHARACTERLOADING";
export const FETCHCHARACTERSUCCESS = "FETCHCHARACTERSUCCESS";
export const FETCHCHARACTERERROR = "FETCHCHARACTERERROR ";

//page
export const CHANGEPAGE = "CHANGEPAGE";

